version: '3.2'
services:
  nginx:
    image: nginx:${NGINX_TAG}
    volumes:
    - ./nginx:/etc/nginx:ro
    - ./nginx/certs:/root/certs
    ports:
    - 443:443
    links:
    - prometheus:prometheus
    - grafana:grafana
    depends_on:
    - prometheus
    - grafana
  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.route-prefix=/
    - --web.external-url=http://localhost/prometheus
    volumes:
    - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    links:
      - prometheus:prometheus
    depends_on:
      - prometheus
